// Merge script — appends new entries to places.json
const fs = require('fs');
const path = require('path');

const placesPath = path.join(__dirname, '..', 'src', 'data', 'places.json');
const existing = JSON.parse(fs.readFileSync(placesPath, 'utf8'));

const newEntries = [
    {
        id: "ram-bagh", slug: "ram-bagh", name: "Ram Bagh", nameHi: "राम बाग", city: "Agra", state: "Uttar Pradesh",
        categories: ["attraction"], tags: ["mughal", "babur", "garden", "oldest-mughal-garden", "yamuna-bank", "peaceful", "photography"],
        tagline: "The oldest Mughal garden in India — where Babur first planted the seeds of an empire and a garden tradition.",
        categoryLabel: "Mughal Pleasure Garden", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        legend: "Babur, homesick for the gardens of Kabul and Samarkand, planted this garden on the Yamuna bank in 1528 — the first charbagh on Indian soil.",
        mood: ["serene", "peaceful", "historic", "meditative"],
        description: ["Ram Bagh, originally named Aram Bagh (Garden of Rest), is the oldest surviving Mughal garden in India. Laid out by Emperor Babur in 1528 on the banks of the Yamuna, it introduced the Persian charbagh (four-quartered garden) style to the Indian subcontinent — a design tradition that would culminate in the gardens of the Taj Mahal.", "The garden features tiered terraces, water channels, fountains, and shaded pavilions. Babur, who famously disliked the heat and dust of India, designed it as a micro-climate of shade and water. After his death in 1530, his body was temporarily interred here before being taken to Kabul.", "Today the garden is tranquil and little-visited. The fountains are dry and the pavilions weathered, but the bones of Babur's original design are still visible — a living archaeology of the Mughal garden tradition."],
        highlights: [{ icon: "🌿", title: "Oldest Mughal Garden", description: "The first charbagh built in India (1528) — ancestor of every Mughal garden." }, { icon: "👑", title: "Babur's Rest", description: "Babur's body was temporarily placed here after death." }, { icon: "💧", title: "Persian Water Design", description: "Tiered terraces with channels and fountains." }],
        visitingInfo: { timings: "Sunrise to Sunset", entryFee: "Indian: ₹25 | Foreign: ₹300", bestSeason: "October to March" },
        bestTime: { timeOfDay: "Morning", why: "Cool and quiet — the garden is at its most peaceful in the early hours." },
        duration: "45 minutes - 1 hour",
        accessibility: { wheelchairAccessible: true, shoesRequired: true, photographyAllowed: true },
        travelTips: ["Located between Itmad-ud-Daulah and Mehtab Bagh — combine all three.", "Very few visitors — ideal for quiet contemplation."],
        location: { lat: 27.1993, lng: 78.0271, mapQuery: "Ram+Bagh+Agra" },
        nearbyPlaces: ["itmad-ud-daulah", "mehtab-bagh", "chini-ka-rauza"],
        historicalPeriod: "Mughal Era (16th Century, 1528)", significance: ["historical", "architectural", "natural"],
        didYouKnow: "Ram Bagh was originally called Aram Bagh (Garden of Rest). Over centuries, local pronunciation corrupted 'Aram' to 'Ram.'"
    },
    {
        id: "mariam-tomb", slug: "mariam-tomb", name: "Mariam's Tomb", nameHi: "मरियम का मकबरा", city: "Agra", state: "Uttar Pradesh",
        categories: ["attraction"], tags: ["mughal", "akbar", "tomb", "red-sandstone", "quiet", "off-beaten-path"],
        tagline: "The tomb of Akbar's wife — a quiet monument to the most religiously tolerant Mughal court.",
        categoryLabel: "Mughal Tomb", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        mood: ["peaceful", "historic", "intimate"],
        description: ["Mariam's Tomb, located near Sikandra, is believed to be the final resting place of Mariam-uz-Zamani (Harkha Bai), Akbar's Rajput Hindu wife and mother of Emperor Jahangir.", "The red sandstone structure sits in a quiet garden that sees almost no visitors. The architecture is restrained but elegant — a single-storey tomb with pierced screens and calligraphic panels.", "The tomb illustrates Akbar's syncretic vision — a Mughal emperor honouring a Hindu wife with a monument blending both architectural traditions."],
        highlights: [{ icon: "👸", title: "Royal Resting Place", description: "Tomb of Akbar's Rajput wife, mother of Emperor Jahangir." }, { icon: "🤫", title: "Hidden Heritage", description: "Almost no tourists visit — deeply quiet and atmospheric." }],
        visitingInfo: { timings: "Sunrise to Sunset", entryFee: "Free", bestSeason: "October to March" },
        bestTime: { timeOfDay: "Anytime", why: "The tomb is quiet at all hours." }, duration: "30 minutes",
        accessibility: { wheelchairAccessible: false, shoesRequired: true, photographyAllowed: true },
        travelTips: ["Located near Sikandra — combine with Akbar's Tomb.", "No entry fee."],
        location: { lat: 27.2192, lng: 77.9516, mapQuery: "Mariam+Tomb+Sikandra+Agra" },
        nearbyPlaces: ["sikandra", "agra-fort"], historicalPeriod: "Mughal Era (16th-17th Century)",
        significance: ["historical", "cultural"],
        didYouKnow: "The identity of the tomb's occupant is still debated — some attribute it to Akbar's mother Hamida Banu Begum."
    },
    {
        id: "sur-sarovar", slug: "sur-sarovar", name: "Sur Sarovar Bird Sanctuary", nameHi: "सूर सरोवर पक्षी अभयारण्य", city: "Agra", state: "Uttar Pradesh",
        categories: ["attraction"], tags: ["wildlife", "birds", "lake", "nature", "sanctuary", "surdas", "peaceful", "family"],
        tagline: "A migratory bird paradise named after the blind poet Surdas — where nature reclaims the Mughal heartland.",
        categoryLabel: "Wildlife Sanctuary", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        mood: ["peaceful", "natural", "serene"],
        description: ["Sur Sarovar Bird Sanctuary (Keetham Lake) is a 7.97 sq km wildlife sanctuary on the outskirts of Agra, named after the poet-saint Surdas. The freshwater lake attracts over 165 species of birds.", "During winter, the lake transforms into a staging ground for migratory birds from Central Asia and Siberia — painted storks, spoonbills, cormorants, and sarus cranes gather by the hundreds.", "For visitors weary of stone monuments, Sur Sarovar offers a green, living counterpoint — proof that Braj holds natural wonders alongside its built heritage."],
        highlights: [{ icon: "🦅", title: "165+ Bird Species", description: "Migratory birds from Siberia, painted storks, sarus cranes." }, { icon: "🐻", title: "Bear Rescue Centre", description: "Wildlife SOS sloth bear rescue facility." }, { icon: "🌿", title: "Surdas Connection", description: "Named after the blind poet-saint who sang of Krishna." }],
        visitingInfo: { timings: "9:00 AM to 5:00 PM", entryFee: "₹30 per person", bestSeason: "November to February" },
        bestTime: { timeOfDay: "Morning", why: "Early mornings bring the best bird activity." }, duration: "2-3 hours",
        accessibility: { wheelchairAccessible: false, shoesRequired: true, photographyAllowed: true },
        travelTips: ["Bring binoculars and telephoto lens.", "Visit in winter for migratory species.", "22 km from central Agra."],
        location: { lat: 27.2432, lng: 77.8698, mapQuery: "Sur+Sarovar+Bird+Sanctuary+Agra" },
        nearbyPlaces: ["sikandra"], historicalPeriod: "Modern (sanctuary established 1991)",
        significance: ["ecological", "natural", "spiritual"],
        didYouKnow: "Named after Surdas, the blind poet-saint who composed over 100,000 devotional verses to Krishna near this lake."
    },
    {
        id: "mankameshwar-temple", slug: "mankameshwar-temple", name: "Mankameshwar Temple", nameHi: "मनकामेश्वर मंदिर", city: "Agra", state: "Uttar Pradesh",
        categories: ["temple"], tags: ["shiva", "ancient", "yamuna-bank", "panch-shiva", "devotional"],
        tagline: "One of five ancient Shiva temples guarding Agra — where wishes whispered to the lingam are said to come true.",
        categoryLabel: "Ancient Shiva Temple", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        legend: "The Shiva lingam here is said to be swayambhu (self-manifested) and fulfills the heart's deepest wishes.",
        mood: ["devotional", "ancient", "sacred", "intimate"],
        description: ["Mankameshwar Temple is one of Agra's oldest and most revered Shiva temples, situated on the Yamuna bank. It is one of five ancient Panch Shiva temples believed to guard the city from the cardinal directions.", "The temple houses a swayambhu Shiva lingam, and 'Mankameshwar' translates to 'Lord who fulfills desires.' Devotees come here with deeply personal prayers.", "The riverside location adds to its atmosphere — the Yamuna combines with temple bells and Sanskrit chanting."],
        highlights: [{ icon: "🕉️", title: "Swayambhu Lingam", description: "Self-manifested Shiva lingam — not carved by human hands." }, { icon: "🛕", title: "Panch Shiva Circuit", description: "One of five ancient Shiva temples guarding Agra." }, { icon: "🌊", title: "Yamuna Riverside", description: "Riverside setting enhances the devotional atmosphere." }],
        visitingInfo: { timings: "5:00 AM to 9:00 PM", entryFee: "Free", bestSeason: "Year-round, especially Shivratri" },
        bestTime: { timeOfDay: "Evening", why: "Evening aarti on the Yamuna bank is deeply moving.", festivals: ["Maha Shivratri", "Sawan"] },
        duration: "30-45 minutes",
        accessibility: { wheelchairAccessible: false, shoesRequired: false, photographyAllowed: false, dressCode: "Conservative attire — remove shoes" },
        travelTips: ["Remove shoes before entering.", "Visit during Maha Shivratri for the most vibrant celebrations.", "Combine with Balkeshwar Temple nearby."],
        location: { lat: 27.1658, lng: 78.0102, mapQuery: "Mankameshwar+Temple+Agra" },
        nearbyPlaces: ["balkeshwar-temple", "yamuna-ghat-agra"], historicalPeriod: "Ancient (pre-Mughal)",
        significance: ["spiritual", "mythological", "pilgrimage"],
        didYouKnow: "The Panch Shiva temples of Agra are said to form a protective ring, predating the city's Mughal identity by centuries."
    },
    {
        id: "jama-masjid-agra", slug: "jama-masjid-agra", name: "Jama Masjid", nameHi: "जामा मस्जिद आगरा", city: "Agra", state: "Uttar Pradesh",
        categories: ["temple", "attraction"], tags: ["mughal", "mosque", "shah-jahan", "red-sandstone", "islamic-architecture"],
        tagline: "Shah Jahan's forgotten masterpiece — a colossal Friday mosque built for his favourite daughter, overshadowed by the Taj.",
        categoryLabel: "Mughal Congregational Mosque", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        legend: "Shah Jahan built this mosque in 1648 and dedicated it to his daughter Jahanara Begum — the princess who nursed him through his final imprisoned years.",
        mood: ["majestic", "devotional", "historic", "serene"],
        description: ["The Jama Masjid of Agra is one of the largest mosques in India, built by Shah Jahan in 1648 for Princess Jahanara Begum. Its towering gateway and twin minarets dominate the old city skyline.", "The mosque follows the classic Mughal congregational plan — a vast courtyard for 10,000 worshippers, arcaded corridors, and a prayer hall with three marble domes.", "Though overshadowed by the Taj, it remains an active place of worship, vibrant during Friday prayers and Eid."],
        highlights: [{ icon: "🕌", title: "One of India's Largest", description: "Courtyard holds over 10,000 worshippers." }, { icon: "👸", title: "Dedicated to Jahanara", description: "Built for Shah Jahan's daughter." }, { icon: "🏛️", title: "Triple-Dome Design", description: "Three white marble domes crown the sandstone prayer hall." }],
        visitingInfo: { timings: "Sunrise to Sunset (restricted during prayers)", entryFee: "Free", bestSeason: "October to March" },
        bestTime: { timeOfDay: "Morning", why: "Visit outside prayer times for exploration.", festivals: ["Eid ul-Fitr", "Eid ul-Adha"] },
        duration: "30-45 minutes",
        accessibility: { wheelchairAccessible: false, shoesRequired: false, photographyAllowed: true, dressCode: "Conservative — women cover heads", entryRestrictions: "Non-Muslims welcome outside prayer times" },
        travelTips: ["Remove shoes.", "Women should carry a head scarf.", "Near Kinari Bazaar — combine for a cultural morning."],
        location: { lat: 27.1786, lng: 78.0195, mapQuery: "Jama+Masjid+Agra" },
        nearbyPlaces: ["agra-fort", "kinari-bazaar"], historicalPeriod: "Mughal Era (17th Century, 1648)",
        significance: ["spiritual", "architectural", "historical"],
        didYouKnow: "The mosque uses the same red sandstone as Agra Fort, quarried from the Fatehpur Sikri ridge."
    },
    {
        id: "soami-bagh-samadhi", slug: "soami-bagh-samadhi", name: "Soami Bagh Samadhi", nameHi: "स्वामी बाग समाधि", city: "Agra", state: "Uttar Pradesh",
        categories: ["temple"], tags: ["radhasoami", "marble-inlay", "ongoing-construction", "devotional", "white-marble"],
        tagline: "A marble masterpiece under construction for over a century — the Radhasoami faith's answer to the Taj Mahal.",
        categoryLabel: "Living Marble Masterwork", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        legend: "Construction began in 1904 and continues to this day — every inch hand-carved using the same pietra dura techniques as the Taj Mahal.",
        mood: ["sacred", "meditative", "majestic", "devotional"],
        description: ["Soami Bagh Samadhi is the mausoleum of Shiv Dayal Singh, founder of the Radhasoami faith. Under continuous construction since 1904, its marble craftsmanship rivals the Taj Mahal.", "Every surface is hand-carved with botanical detail: flowers with individually inlaid petals, insects so lifelike they seem to breathe. The artisans are descendants of Taj Mahal craftsmen.", "The project has no fixed completion date. The community sees the building as an offering — the act of carving is as sacred as the finished product."],
        highlights: [{ icon: "💎", title: "Unmatched Marble Inlay", description: "Pietra dura of extraordinary precision." }, { icon: "🔨", title: "Century of Construction", description: "Ongoing since 1904 by hereditary artisan families." }, { icon: "🌺", title: "Botanical Realism", description: "Stone flowers with individually inlaid petals." }],
        visitingInfo: { timings: "8:00 AM to 5:00 PM", entryFee: "Free", bestSeason: "October to March" },
        bestTime: { timeOfDay: "Morning", why: "Morning light illuminates the marble carvings." }, duration: "1 hour",
        accessibility: { wheelchairAccessible: false, shoesRequired: false, photographyAllowed: false, dressCode: "Conservative attire" },
        travelTips: ["Photography strictly prohibited.", "Remove shoes.", "10 km from central Agra.", "Ask to see the artisans' workshop."],
        location: { lat: 27.2324, lng: 77.9946, mapQuery: "Soami+Bagh+Samadhi+Agra" },
        nearbyPlaces: ["dayal-bagh", "sikandra"], historicalPeriod: "Modern (1904–ongoing)",
        significance: ["spiritual", "architectural", "cultural"],
        didYouKnow: "The artisans are direct descendants of the families who built the Taj Mahal — the last living link to Mughal craftsmanship."
    },
    {
        id: "balkeshwar-temple", slug: "balkeshwar-temple", name: "Balkeshwar Temple", nameHi: "बालकेश्वर मंदिर", city: "Agra", state: "Uttar Pradesh",
        categories: ["temple"], tags: ["shiva", "ancient", "panch-shiva", "yamuna-bank", "devotional"],
        tagline: "An ancient Shiva sentinel on the Yamuna — one of five temples guarding Agra since before the Mughals.",
        categoryLabel: "Ancient Shiva Temple", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        legend: "Balkeshwar is said to protect children — mothers bring infants here for blessings.",
        mood: ["devotional", "ancient", "sacred", "intimate"],
        description: ["Balkeshwar Temple is one of Agra's Panch Shiva temples — five ancient shrines guarding the city from cardinal directions. On the Yamuna bank, it predates the Mughal period.", "Intimately associated with children's welfare, mothers bring newborns for blessings. The annual Balkeshwar Mela draws families from across the region."],
        highlights: [{ icon: "🕉️", title: "Panch Shiva", description: "One of five directional guardian Shiva temples." }, { icon: "👶", title: "Children's Protector", description: "Mothers bring infants for blessings." }],
        visitingInfo: { timings: "5:00 AM to 9:00 PM", entryFee: "Free", bestSeason: "Year-round" },
        bestTime: { timeOfDay: "Evening", why: "Evening aarti on the Yamuna steps is atmospheric." }, duration: "30 minutes",
        accessibility: { wheelchairAccessible: false, shoesRequired: false, photographyAllowed: false, dressCode: "Conservative attire" },
        travelTips: ["Remove shoes.", "Combine with Mankameshwar Temple.", "Visit during evening aarti."],
        location: { lat: 27.1642, lng: 78.0089, mapQuery: "Balkeshwar+Temple+Agra" },
        nearbyPlaces: ["mankameshwar-temple", "yamuna-ghat-agra"], historicalPeriod: "Ancient (pre-Mughal)",
        significance: ["spiritual", "mythological", "pilgrimage"],
        didYouKnow: "The Panch Shiva temples — Balkeshwar, Mankameshwar, Prithvinath, Kailash, and Rajarajeshwar — predate all Mughal-era monuments in Agra."
    },
    {
        id: "kailash-temple-agra", slug: "kailash-temple-agra", name: "Kailash Temple", nameHi: "कैलाश मंदिर", city: "Agra", state: "Uttar Pradesh",
        categories: ["temple"], tags: ["shiva", "panch-shiva", "ancient", "quiet", "devotional"],
        tagline: "The silent Shiva — a rarely visited guardian temple near the Fort.",
        categoryLabel: "Ancient Shiva Temple", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        mood: ["peaceful", "devotional", "ancient"],
        description: ["Kailash Temple is one of the five Panch Shiva temples guarding Agra. Located near Agra Fort, this serene shrine offers a quiet counterpoint to monumental tourism.", "Local devotees maintain the temple with love. Few tourists come, making it a genuine glimpse into Agra's pre-Mughal spiritual life."],
        highlights: [{ icon: "🕉️", title: "Panch Shiva Guardian", description: "One of five ancient sentinels." }, { icon: "🤫", title: "Unvisited Sanctuary", description: "Almost no tourists — a genuine devotional experience." }],
        visitingInfo: { timings: "5:00 AM to 8:00 PM", entryFee: "Free", bestSeason: "Year-round" },
        bestTime: { timeOfDay: "Morning", why: "Morning puja fills the temple with bells and fragrance." }, duration: "20 minutes",
        accessibility: { wheelchairAccessible: false, shoesRequired: false, photographyAllowed: false },
        travelTips: ["Near Agra Fort — combine visits.", "Remove shoes."],
        location: { lat: 27.1780, lng: 78.0180, mapQuery: "Kailash+Temple+Agra" },
        nearbyPlaces: ["agra-fort", "jama-masjid-agra"], historicalPeriod: "Ancient (pre-Mughal)",
        significance: ["spiritual", "mythological"],
        didYouKnow: "Named after Mount Kailash, the mythological abode of Lord Shiva in the Himalayas."
    },
    {
        id: "prithvinath-temple", slug: "prithvinath-temple", name: "Prithvinath Temple", nameHi: "पृथ्वीनाथ मंदिर", city: "Agra", state: "Uttar Pradesh",
        categories: ["temple"], tags: ["shiva", "panch-shiva", "ancient", "hillside", "panoramic-view", "devotional"],
        tagline: "A hillside Shiva temple with panoramic views — one of the five ancient guardians of Agra.",
        categoryLabel: "Hilltop Shiva Temple", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        legend: "The hilltop was chosen because Shiva's gaze from this elevation was believed to protect the entire city from calamity.",
        mood: ["devotional", "peaceful", "ancient"],
        description: ["Prithvinath Temple sits on a low hill overlooking the city, one of the five Panch Shiva temples. The elevation offers unexpected panoramic views of Agra's skyline.", "The temple is maintained by a small community of devotees and sees virtually no tourist traffic — a raw, unpolished devotional site."],
        highlights: [{ icon: "🕉️", title: "Panch Shiva", description: "One of five directional guardian Shiva temples." }, { icon: "🏔️", title: "Hilltop Views", description: "Panoramic views of Agra from the temple elevation." }],
        visitingInfo: { timings: "6:00 AM to 8:00 PM", entryFee: "Free", bestSeason: "October to March" },
        bestTime: { timeOfDay: "Evening", why: "Sunset views from the hilltop are unexpectedly beautiful." }, duration: "30 minutes",
        accessibility: { wheelchairAccessible: false, shoesRequired: false, photographyAllowed: true },
        travelTips: ["Ask locals for directions — not well signposted.", "The climb is short but steep."],
        location: { lat: 27.1700, lng: 78.0150, mapQuery: "Prithvinath+Temple+Agra" },
        nearbyPlaces: ["mankameshwar-temple", "balkeshwar-temple"], historicalPeriod: "Ancient (pre-Mughal)",
        significance: ["spiritual", "mythological"],
        didYouKnow: "Prithvinath means 'Lord of the Earth' — the temple honours Shiva in his aspect as protector of the physical world."
    },
    {
        id: "dayal-bagh", slug: "dayal-bagh", name: "Dayal Bagh Temple", nameHi: "दयालबाग मंदिर", city: "Agra", state: "Uttar Pradesh",
        categories: ["temple", "attraction"], tags: ["radhasoami", "white-marble", "spiritual-community"],
        tagline: "A self-sufficient spiritual township where marble artisans carry forward a century-old sacred craft.",
        categoryLabel: "Spiritual Township", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        mood: ["peaceful", "devotional", "meditative"],
        description: ["Dayal Bagh is the headquarters of the Radhasoami Satsang Sabha, about 15 km from central Agra. It is a self-sufficient spiritual community with schools, hospitals, farms, and workshops.", "The marble carving workshops display extraordinary skill — artisans produce everything from decorative panels to architectural elements using traditional hand tools."],
        highlights: [{ icon: "🏘️", title: "Self-Sufficient Township", description: "Schools, hospitals, farms run by the spiritual community." }, { icon: "🔨", title: "Living Craft", description: "Marble carving workshops preserve traditional skills." }],
        visitingInfo: { timings: "9:00 AM to 5:00 PM", entryFee: "Free", bestSeason: "October to March" },
        bestTime: { timeOfDay: "Morning", why: "The community is most active in the morning." }, duration: "1 hour",
        accessibility: { wheelchairAccessible: true, shoesRequired: false, photographyAllowed: false },
        travelTips: ["Visit the marble workshops.", "Photography restricted in religious areas.", "Near Soami Bagh — combine both."],
        location: { lat: 27.2380, lng: 77.9898, mapQuery: "Dayal+Bagh+Agra" },
        nearbyPlaces: ["soami-bagh-samadhi", "sikandra"], historicalPeriod: "Modern (early 20th Century)",
        significance: ["spiritual", "cultural"],
        didYouKnow: "Dayal Bagh operates one of India's most successful self-sufficient communes, with its own internal economy and some of the finest marble artisans in India."
    },
    {
        id: "guru-ka-tal", slug: "guru-ka-tal", name: "Gurudwara Guru Ka Tal", nameHi: "गुरुद्वारा गुरु का ताल", city: "Agra", state: "Uttar Pradesh",
        categories: ["temple", "attraction"], tags: ["sikh", "gurudwara", "guru-tegh-bahadur", "sacred-tank", "peaceful"],
        tagline: "A grand Sikh shrine built where Guru Tegh Bahadur was imprisoned — one of India's largest and least-known gurudwaras.",
        categoryLabel: "Historic Sikh Shrine", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        legend: "Guru Tegh Bahadur was imprisoned at this site by Aurangzeb before his execution in Delhi — the gurudwara honours his sacrifice for religious freedom.",
        mood: ["sacred", "peaceful", "historic", "grand"],
        description: ["Gurudwara Guru Ka Tal is one of India's largest gurudwaras, commemorating where the ninth Sikh Guru was held prisoner by Aurangzeb in 1665.", "The complex centres on a sacred tank and features a massive prayer hall and langar (community kitchen) feeding hundreds daily. Despite its importance, it sees remarkably few non-Sikh visitors.", "The langar is open to all faiths — a practical demonstration of the Sikh principle of equality."],
        highlights: [{ icon: "🛕", title: "Historic Site", description: "Where Guru Tegh Bahadur was held by Aurangzeb." }, { icon: "🍱", title: "Open Langar", description: "Free community kitchen — all faiths welcome." }, { icon: "💧", title: "Sacred Tank", description: "Holy tank central to the gurudwara complex." }],
        visitingInfo: { timings: "Open 24 hours", entryFee: "Free", bestSeason: "Year-round" },
        bestTime: { timeOfDay: "Morning", why: "Morning kirtan is deeply moving." }, duration: "1 hour",
        accessibility: { wheelchairAccessible: true, shoesRequired: false, photographyAllowed: true, dressCode: "Head must be covered — scarves provided" },
        travelTips: ["Cover your head — scarves available at the gate.", "Remove shoes.", "The langar serves free meals — don't miss it."],
        location: { lat: 27.1926, lng: 78.0020, mapQuery: "Gurudwara+Guru+Ka+Tal+Agra" },
        nearbyPlaces: ["jama-masjid-agra", "agra-fort"], historicalPeriod: "Mughal Era (17th Century, 1665)",
        significance: ["spiritual", "historical", "pilgrimage"],
        didYouKnow: "Guru Tegh Bahadur was executed for defending the religious freedom of Kashmiri Pandits — an act central to Sikh identity."
    },
    {
        id: "kinari-bazaar", slug: "kinari-bazaar", name: "Kinari Bazaar", nameHi: "किनारी बाज़ार", city: "Agra", state: "Uttar Pradesh",
        categories: ["attraction"], tags: ["market", "shopping", "petha", "marble-inlay", "leather", "old-agra", "food", "vibrant"],
        tagline: "The sparkling heart of old Agra — marble inlay, petha sweets, and leather craft in centuries-old lanes.",
        categoryLabel: "Historic Market", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        mood: ["vibrant", "lively", "festive", "intimate"],
        description: ["Kinari Bazaar is Agra's oldest and most vibrant market, tucked behind the Jama Masjid. The narrow streets overflow with marble inlay work, petha sweets, hand-embroidered fabrics, and leather goods.", "This is where Agra lives — artisans carve marble using hand tools, sweet-makers stir copper vats of petha, and shopkeepers call out in Hindi and Urdu.", "For visitors wanting the real Agra beyond monuments, Kinari Bazaar is essential."],
        highlights: [{ icon: "💎", title: "Marble Inlay Shopping", description: "Pietra dura artisans selling from workshops." }, { icon: "🍬", title: "Petha Capital", description: "Agra's signature sweet at dozens of legendary shops." }, { icon: "👜", title: "Leather Craft", description: "Famous since Mughal times." }],
        visitingInfo: { timings: "10:00 AM to 9:00 PM (closed Sundays)", entryFee: "Free", bestSeason: "October to March" },
        bestTime: { timeOfDay: "Evening", why: "The bazaar comes alive with lights, crowds, and fresh petha." }, duration: "1-2 hours",
        accessibility: { wheelchairAccessible: false, shoesRequired: true, photographyAllowed: true },
        travelTips: ["Bargain firmly — initial prices are 2-3x actual value.", "Try petha from Panchhi Petha.", "Watch out for pickpockets.", "Adjacent to Jama Masjid."],
        location: { lat: 27.1783, lng: 78.0189, mapQuery: "Kinari+Bazaar+Agra" },
        nearbyPlaces: ["jama-masjid-agra", "agra-fort"], historicalPeriod: "Mughal Era",
        significance: ["cultural", "historical"],
        didYouKnow: "The marble inlay artisans of Kinari Bazaar are descendants of the craftsmen who built the Taj Mahal — using the same hand tools and techniques from the 17th century."
    },
    {
        id: "yamuna-ghat-agra", slug: "yamuna-ghat-agra", name: "Yamuna Ghats (Agra)", nameHi: "यमुना घाट (आगरा)", city: "Agra", state: "Uttar Pradesh",
        categories: ["ghat"], tags: ["yamuna", "ghat", "riverside", "aarti", "sunrise", "devotional"],
        tagline: "The forgotten riverfront of the Mughals — where the Yamuna still reflects the domes of a vanished empire.",
        categoryLabel: "Sacred River Ghat", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        legend: "The Yamuna at Agra once flowed clear and deep — the Mughals built their greatest monuments on its banks because the river was sacred.",
        mood: ["serene", "devotional", "ancient", "meditative"],
        description: ["The Yamuna ghats of Agra stretch along the river that inspired the Mughal emperors. Many stone steps are centuries old.", "Early morning visitors witness timeless scenes — women performing puja, fishermen casting nets, and the Taj and Fort silhouettes through river mist."],
        highlights: [{ icon: "🌊", title: "Sacred Yamuna", description: "Ancient stone steps connecting temples to the holy Yamuna." }, { icon: "🌅", title: "Sunrise Views", description: "Dawn reveals Taj and Fort silhouettes through mist." }],
        visitingInfo: { timings: "Open 24 hours", entryFee: "Free", bestSeason: "October to February" },
        bestTime: { timeOfDay: "Dawn", why: "Sunrise over the Yamuna with the Taj silhouette through mist." }, duration: "30-45 minutes",
        accessibility: { wheelchairAccessible: false, shoesRequired: true, photographyAllowed: true },
        travelTips: ["Visit at dawn for atmosphere.", "Steps can be slippery.", "Near Balkeshwar and Mankameshwar temples."],
        location: { lat: 27.1660, lng: 78.0110, mapQuery: "Yamuna+Ghat+Agra" },
        nearbyPlaces: ["balkeshwar-temple", "mankameshwar-temple"], historicalPeriod: "Ancient (pre-Mughal onwards)",
        significance: ["spiritual", "historical"],
        didYouKnow: "In Mughal times, the Yamuna was crystal clear and emperors took evening boat rides between riverside gardens."
    },
    {
        id: "balkeshwar-ghat", slug: "balkeshwar-ghat", name: "Balkeshwar Ghat", nameHi: "बालकेश्वर घाट", city: "Agra", state: "Uttar Pradesh",
        categories: ["ghat"], tags: ["yamuna", "ghat", "devotional", "local", "sunrise", "aarti"],
        tagline: "The devotional heart of Agra's riverfront — where the Yamuna, temple bells, and five centuries of prayer converge.",
        categoryLabel: "Sacred Yamuna Ghat", heroImage: "/agra/attractions/Taj-Mahal.jpeg", gallery: [],
        mood: ["devotional", "serene", "ancient", "intimate"],
        description: ["Balkeshwar Ghat adjoins the ancient Balkeshwar Shiva Temple and is one of Agra's most actively used bathing ghats, especially during Kartik Purnima and Chhath Puja.", "An intimate, non-touristic window into Agra's living religious life — far from the Taj, this is where the devotional heartbeat is strongest."],
        highlights: [{ icon: "🌊", title: "Active Ritual Ghat", description: "Ancient steps used daily for ritual Yamuna bathing." }, { icon: "🛕", title: "Temple Adjacent", description: "Next to Balkeshwar Temple — combine both." }],
        visitingInfo: { timings: "Open 24 hours", entryFee: "Free", bestSeason: "October to March" },
        bestTime: { timeOfDay: "Dawn", why: "Dawn ablutions with temple bells — deeply atmospheric." }, duration: "20 minutes",
        accessibility: { wheelchairAccessible: false, shoesRequired: true, photographyAllowed: true },
        travelTips: ["Visit at dawn.", "Combine with Balkeshwar Temple and Mankameshwar Temple."],
        location: { lat: 27.1645, lng: 78.0092, mapQuery: "Balkeshwar+Ghat+Agra" },
        nearbyPlaces: ["balkeshwar-temple", "mankameshwar-temple", "yamuna-ghat-agra"], historicalPeriod: "Ancient",
        significance: ["spiritual", "pilgrimage"],
        didYouKnow: "During Chhath Puja, thousands gather at this ghat before dawn to offer prayers to the rising sun — a tradition unbroken for centuries."
    }
];

const merged = [...existing, ...newEntries];
fs.writeFileSync(placesPath, JSON.stringify(merged, null, 2), 'utf8');
console.log(`✅ Merged: ${existing.length} existing + ${newEntries.length} new = ${merged.length} total entries`);
